<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="59596" started-at="2016-04-19T05:45:49Z" finished-at="2016-04-19T05:46:48Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="59596" started-at="2016-04-19T05:45:49Z" finished-at="2016-04-19T05:46:48Z">
      <class name="com.sample.selenium.test.TestPage">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.sample.selenium.test.TestPage@5594a1b5]" name="setUp" is-config="true" duration-ms="19955" started-at="2016-04-18T22:45:49Z" finished-at="2016-04-18T22:46:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="test01()[pri:0, instance:com.sample.selenium.test.TestPage@5594a1b5]" name="test01" duration-ms="17330" started-at="2016-04-18T22:46:09Z" finished-at="2016-04-18T22:46:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test01 -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.sample.selenium.test.TestPage@5594a1b5]" name="tearDown" is-config="true" duration-ms="2259" started-at="2016-04-18T22:46:26Z" finished-at="2016-04-18T22:46:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.sample.selenium.test.TestPage@5594a1b5]" name="setUp" is-config="true" duration-ms="12127" started-at="2016-04-18T22:46:28Z" finished-at="2016-04-18T22:46:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="test02()[pri:0, instance:com.sample.selenium.test.TestPage@5594a1b5]" name="test02" duration-ms="6051" started-at="2016-04-18T22:46:41Z" finished-at="2016-04-18T22:46:47Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Link not found]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Link not found
	at org.testng.Assert.fail(Assert.java:94)
	at com.sample.selenium.commons.Commons.clickByXpath(Commons.java:68)
	at com.sample.selenium.pagefactory.LocateServicePage.linkSearchDoctors(LocateServicePage.java:22)
	at com.sample.selenium.test.TestPage.test02(TestPage.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test02 -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.sample.selenium.test.TestPage@5594a1b5]" name="tearDown" is-config="true" duration-ms="1808" started-at="2016-04-18T22:46:47Z" finished-at="2016-04-18T22:46:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.sample.selenium.test.TestPage -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
